// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthSchema from "../models/drizzle/auth.model";
import * as HistorySchema from "../models/drizzle/history.model";
import * as RelationSchema from "../models/drizzle/relation.model";
import * as TransactionsSchema from "../models/drizzle/transactions.model";

const schema = {
	...AuthSchema,
	...HistorySchema,
	...RelationSchema,
	...TransactionsSchema
};

export default schema;
